# How to assign multipkle lne string to a variable 

'''
like, this= "Hello my name is Aditya and 
here I am learning Python and I am loving it"


But this is not the correct way to assign a multi line string to a variable, we can use triple quotes for that purpose, like this:

'''


multi_line_string = """Hello my name is Aditya and
here I am learning Python and I am loving it"""


# Now withing those triple quotes we can write as many lines as we want and it will be assigned to the variable multi_line_string without any issues.


multi_line_string2 = '''This is another way to assign a multi line string to a variable using triple single quotes.
This is also perfectly valid and works the same way as triple double quotes.
You can choose either of them based on your preference or the need to include certain types of quotes within the string.'''